export const techData = [
  {
    title: "VS Code",
    icon: "vscode-original",
    id: 0,
    desc: "Best coding IDE to ever exist, comes with tons of customization",
    tag: "code",
    bg: "bg-blue-50",
    text: "text-blue-500",
    viewbox: "0 0 128 128",
  },
  {
    title: "JavaScript",
    icon: "javascript-original",
    id: 1,
    desc: "A lightweight, interpreted, or just-in-time compiled programming language with first-class functions.",
    tag: "code",
    bg: "bg-yellow-50",
    text: "text-yellow-500",
    viewbox: "0 0 128 128",
  },
  {
    title: "TypeScript",
    icon: "typescript-original",
    id: 2,
    desc: "SuperScript of Javascript, made by microsoft with robust type safety.",
    tag: "code",
    bg: "bg-blue-50",
    text: "text-blue-500",
    viewbox: "0 0 128 128",
  },
  {
    title: "Python",
    icon: "python-original",
    id: 3,
    desc: "Python, a powerful, readable, and versatile programming language.",
    tag: "code",
    bg: "bg-blue-50",
    text: "text-blue-500",
    viewbox: "0 0 32 32",
  },
  {
    title: "React JS",
    icon: "react-original",
    id: 4,
    desc: "A free and open-source front-end JavaScript library for building user interfaces based on components",
    tag: "develop",
    bg: "bg-blue-50",
    text: "text-blue-500",
    viewbox: "0 0 128 128",
  },
  {
    title: "Next JS",
    icon: "next-original",
    id: 5,
    desc: "An open-source web development framework providing React-based web applications.",
    tag: "develop",
    bg: "bg-gray-900",
    text: "text-gray-50",
    viewbox: "0 0 128 128",
  },
  {
    title: "Tailwind CSS",
    icon: "tailwindcss-original",
    id: 6,
    desc: "A utility-first CSS framework for rapidly building modern websites without ever leaving your HTML.",
    tag: "design",
    bg: "bg-green-50",
    text: "text-green-500",
    viewbox: "0 0 129 128",
  },
  {
    title: "Material UI",
    icon: "materialui-original",
    id: 7,
    desc: "A comprehensive suite of UI tools to help you ship new features faster.",
    tag: "develop",
    bg: "bg-indigo-50",
    text: "text-indigo-500",
    viewbox: "0 0 128 128",
  },
  {
    title: "GraphQL",
    icon: "graphql-original",
    id: 8,
    desc: "A modern query language and runtime for APIs, providing a flexible and efficient approach to request and deliver data.",
    tag: "develop",
    bg: "bg-red-50",
    text: "text-red-500",
    viewbox: "0 0 32 32",
  },
  {
    title: "GitHub",
    icon: "github-original",
    id: 9,
    desc: "A developer's go-to platform for collaborating and showcasing their code.",
    tag: "platform",
    bg: "bg-gray-900",
    text: "text-gray-100",
    viewbox: "0 0 128 128",
  },
];
