export const techData = [
  {
    title: "VS Code",
    icon: "vs-code",
    id: 0,
    main: "/assets/icons/vscode-original.svg",
    desc: "Best coding IDE to ever exist, comes with tons of customization",
    tag: "code",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "JavaScript",
    id: 1,
    main: "/assets/icons/javascript-original.svg",
    desc: "A lightweight, interpreted, or just-in-time compiled programming language with first-class functions.",
    tag: "code",
    bg: "bg-yellow-50",
    text: "text-yellow-500",
  },
  {
    title: "TypeScript",
    id: 2,
    main: "/assets/icons/typescript-plain.svg",
    desc: "SuperScript of Javascript, made by microsoft with robust type safety.",
    tag: "code",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "React JS",
    id: 3,
    main: "/assets/icons/react-original.svg",
    desc: "A free and open-source front-end JavaScript library for building user interfaces based on components",
    tag: "develop",
    bg: "bg-blue-50",
    text: "text-blue-500",
  },
  {
    title: "Next JS",
    id: 4,
    main: "assets/icons/nextjs-original.svg",
    desc: "An open-source web development framework providing React-based web applications.",
    tag: "develop",
    bg: "bg-gray-900",
    text: "text-gray-50",
  },
  {
    title: "Tailwind CSS",
    id: 5,
    main: "assets/icons/tailwindcss-plain.svg",
    desc: "A utility-first CSS framework for rapidly building modern websites without ever leaving your HTML.",
    tag: "design",
    bg: "bg-green-50",
    text: "text-green-500",
  },
  {
    title: "Material UI",
    id: 6,
    main: "assets/icons/materialui-original.svg",
    desc: "A comprehensive suite of UI tools to help you ship new features faster.",
    tag: "develop",
    bg: "bg-indigo-50",
    text: "text-indigo-500",
  },
  {
    title: "GitHub",
    id: 7,
    main: "/assets/icons/github-original.svg",
    desc: "A developer's go-to platform for collaborating and showcasing their code.",
    tag: "platform",
    bg: "bg-gray-900",
    text: "text-gray-100",
  },
];
